// Personas (LDAP → Keycloak → Vault OIDC). Passwords are generated by
// `make identity-up` into .secrets/identity/users.json — never hardcoded.
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

export const USERS = ['ada', 'ben', 'cleo', 'dirk', 'eve', 'finn'] as const
export type User = (typeof USERS)[number]

export const ROOT = resolve(import.meta.dirname, '..', '..')
export const stateFile = (u: User) => resolve(import.meta.dirname, '.auth', `${u}.json`)

let cache: Record<string, string> | null = null
export function passwordOf(u: User): string {
  cache ??= JSON.parse(readFileSync(resolve(ROOT, '.secrets/identity/users.json'), 'utf8'))
  const p = cache![u]
  if (!p) throw new Error(`no password for ${u} in .secrets/identity/users.json — run make identity-up`)
  return p
}
